# Generated by Django 6.0.7 on 2026-08-01 05:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_author', models.CharField(blank=True, default='Unknown', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_category', models.CharField(blank=True, default='Unknown', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(default=None, max_length=100, unique=True)),
                ('phone', models.CharField(default='', max_length=10)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('libby', 'Libby')], default='user', max_length=25)),
                ('name', models.CharField(blank=True, default='Unknown', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_book', models.CharField(blank=True, default='Unknown', max_length=100)),
                ('total', models.IntegerField(default=0)),
                ('total_borrowed', models.IntegerField(default=0)),
                ('total_error', models.IntegerField(default=0)),
                ('content', models.TextField(default='')),
                ('author', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.author')),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('borrow_date', models.DateField()),
                ('borrow_status', models.CharField(choices=[('borrowed', 'Borrowed'), ('returned', 'Returned'), ('overdue', 'Overdue')], default='borrowed', max_length=25)),
                ('due_date', models.DateField()),
                ('book', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.book')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fines',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fine_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('borrow', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.borrow')),
            ],
        ),
    ]
