# Generated by Django 6.0.7 on 2026-08-03 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name_author',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='name_book',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name_category',
            new_name='name',
        ),
    ]
