# Generated by Django 5.2.17 on 2026-08-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_book_author_alter_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='fine_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Fines',
        ),
    ]
