# Generated by Django 5.2.17 on 2026-08-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_borrow_fine_amount_delete_fines'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='returned_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
