# Generated by Django 5.2.17 on 2026-08-09 08:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_book_author_remove_book_category_book_authors_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrow',
            old_name='returned_date',
            new_name='payment_date',
        ),
        migrations.RemoveField(
            model_name='borrow',
            name='book',
        ),
        migrations.AlterField(
            model_name='borrow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BorrowBook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('book_quantity', models.IntegerField(default=1)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.book')),
                ('borrow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_books', to='api.borrow')),
            ],
        ),
    ]
